export const emeraldTheme = {
  name: 'Emerald',
  gradient: 'bg-gradient-to-br from-emerald-400 via-emerald-50 to-white',
  accent: 'bg-emerald-600',
  accentHover: 'hover:bg-emerald-700',
  accentFocus: 'focus:ring-2 focus:ring-emerald-500 focus:ring-offset-2',
  blur: 'bg-emerald-50/70',
  text: 'text-emerald-600',
  border: 'border-emerald-200',
  colors: {
    primary: 'bg-emerald-600',
    primaryLight: 'bg-emerald-500',
    primaryDark: 'bg-emerald-700',
    primaryText: 'text-emerald-600',
    secondary: 'bg-emerald-100',
    secondaryHover: 'hover:bg-emerald-200',
    card: 'bg-white/80',
    cardHover: 'hover:bg-white/90',
    sidebar: 'bg-white/90',
    header: 'bg-white/90',
    hover: 'hover:bg-emerald-50',
    muted: 'text-emerald-600/60',
    mutedHover: 'hover:text-emerald-600',
    divider: 'border-emerald-100',
    success: 'text-green-600',
    warning: 'text-amber-600',
    error: 'text-red-600',
    info: 'text-blue-600',
    surface: 'bg-white dark:bg-gray-800',
    surfaceHover: 'hover:bg-gray-50 dark:hover:bg-gray-700'
  },
  badges: {
    default: 'bg-emerald-100 text-emerald-700',
    new: 'bg-green-100 text-green-700',
    success: 'bg-green-100 text-green-700',
    warning: 'bg-amber-100 text-amber-700',
    error: 'bg-red-100 text-red-700',
    info: 'bg-blue-100 text-blue-700'
  },
  status: {
    online: 'bg-green-500',
    offline: 'bg-gray-500',
    busy: 'bg-red-500',
    away: 'bg-amber-500'
  },
  components: {
    input: 'bg-white/50 border border-emerald-200 rounded-lg',
    inputFocus: 'focus:ring-2 focus:ring-emerald-500 focus:border-emerald-500',
    button: 'bg-emerald-600 text-white',
    buttonHover: 'hover:bg-emerald-700',
    card: 'bg-white/80 backdrop-blur-sm border border-emerald-100',
    cardHover: 'hover:bg-white/90 hover:shadow-lg',
    dropdown: 'bg-white border border-emerald-100 shadow-lg rounded-lg',
    dropdownHover: 'hover:bg-emerald-50',
    tooltip: 'bg-gray-900 text-white px-2 py-1 rounded text-sm',
    modal: 'bg-white shadow-xl rounded-lg',
    toast: 'bg-white shadow-lg rounded-lg border-l-4'
  },
  dark: {
    gradient: 'bg-gradient-to-br from-emerald-900 via-gray-900 to-black',
    accent: 'bg-emerald-500',
    accentHover: 'hover:bg-emerald-600',
    text: 'text-emerald-400',
    border: 'border-emerald-800',
    colors: {
      primary: 'bg-emerald-500',
      primaryLight: 'bg-emerald-400',
      primaryDark: 'bg-emerald-600',
      primaryText: 'text-emerald-400',
      secondary: 'bg-emerald-900/50',
      secondaryHover: 'hover:bg-emerald-800/50',
      card: 'bg-gray-800/80',
      cardHover: 'hover:bg-gray-800/90',
      sidebar: 'bg-gray-900/90',
      header: 'bg-gray-900/90',
      hover: 'hover:bg-emerald-900/50',
      muted: 'text-emerald-400/60',
      mutedHover: 'hover:text-emerald-400',
      divider: 'border-emerald-800',
      surface: 'bg-gray-900',
      surfaceHover: 'hover:bg-gray-800'
    }
  }
} as const;
