// modules/ueSim/services/cfgEmitter.ts
//
// Emits a valid Amarisoft ue.cfg from the six section data shapes.
// The reverse of sectionMapper.mapToSections.
//
// Output style: pretty-printed JSON-with-comments, 2-space indent. Keys
// are emitted in a stable order so re-emit is deterministic (important
// for git diffs and round-trip tests).
//
// CRITICAL DESIGN POINT — power_on + duration → power_off:
//   The Traffic tab lets the operator declare "UE is active for N seconds
//   starting at t=T". That single intent maps to *two* Amarisoft sim_events:
//
//       { event: "power_on",  start_time: T }
//       { event: "power_off", start_time: T + N }
//
//   The emitter performs this expansion. The Traffic tab's UI surfaces a
//   single "duration" field on power_on events; the user never sees the
//   power_off because it's derived. On import (sectionMapper), an existing
//   power_off paired with a power_on collapses back into a duration when
//   the times match — though we do not currently auto-collapse to keep
//   round-trip explicit; the user can clean up manually.

import {
  CellGroupSpec,
  CellSpec,
  CustomBandSpec,
  MaterializedProfile,
  PerCellChannel,
  SimEvent,
  SubscriberEntry,
  UeMobility,
  UeAssignment,
  TrafficTemplate,
  LayerLogConfig,
} from '../types';

// ────────────────────────────────────────────────────────────────────────────
// Pretty printer — supports comments at the top
// ────────────────────────────────────────────────────────────────────────────

interface EmitOptions {
  /** When true, emit a /* generated by simtool * / header comment. */
  header?: boolean;
}

function indent(s: string, level: number): string {
  const pad = '  '.repeat(level);
  return s.split('\n').map(line => line ? pad + line : line).join('\n');
}

function emitValue(v: unknown, level: number): string {
  if (v === null || v === undefined) return 'null';
  if (typeof v === 'boolean') return v ? 'true' : 'false';
  if (typeof v === 'number') return Number.isFinite(v) ? String(v) : '0';
  if (typeof v === 'string') return JSON.stringify(v);
  if (Array.isArray(v)) return emitArray(v, level);
  if (typeof v === 'object') return emitObject(v as Record<string, unknown>, level);
  return JSON.stringify(v);
}

function emitArray(a: unknown[], level: number): string {
  if (a.length === 0) return '[]';
  // Decide one-line vs multi-line: scalars only → one-line
  const allScalar = a.every(
    x => x === null || ['string', 'number', 'boolean'].includes(typeof x),
  );
  if (allScalar) {
    return '[' + a.map(x => emitValue(x, level)).join(', ') + ']';
  }
  const parts = a.map(x => indent(emitValue(x, 0), level + 1));
  return '[\n' + parts.join(',\n') + '\n' + '  '.repeat(level) + ']';
}

function emitObject(o: Record<string, unknown>, level: number): string {
  const entries = Object.entries(o).filter(([, v]) => v !== undefined);
  if (entries.length === 0) return '{}';
  const lines = entries.map(([k, v]) => {
    return indent(`${k}: ${emitValue(v, level + 1)}`, level + 1);
  });
  return '{\n' + lines.join(',\n') + '\n' + '  '.repeat(level) + '}';
}

// ────────────────────────────────────────────────────────────────────────────
// Section-specific emitters — produce raw JS objects, then pretty-print
// ────────────────────────────────────────────────────────────────────────────

/**
 * Build a cell record with channel info merged in, in a stable key order.
 * Stable order is essential for byte-for-byte round-trip equivalence.
 */
function buildCellRecord(c: CellSpec, ch: PerCellChannel | undefined): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  // Identification
  out.rf_port = c.rf_port;
  out.bandwidth = c.bandwidth;
  if (c.dl_earfcn != null) out.dl_earfcn = c.dl_earfcn;
  if (c.dl_nr_arfcn != null) out.dl_nr_arfcn = c.dl_nr_arfcn;
  if (c.ul_earfcn != null) out.ul_earfcn = c.ul_earfcn;
  if (c.ul_carrier_freq_offset != null) out.ul_carrier_freq_offset = c.ul_carrier_freq_offset;
  // Antennas
  out.n_antenna_dl = c.n_antenna_dl;
  out.n_antenna_ul = c.n_antenna_ul;
  // NR-specific
  if (c.scs != null) out.scs = c.scs;
  if (c.ssb_pos_bitmap != null) out.ssb_pos_bitmap = c.ssb_pos_bitmap;
  if (c.tdd_config != null) out.tdd_config = c.tdd_config;
  // Per-cell extras (preserved unknown keys)
  if (c._extra) Object.assign(out, c._extra);
  // Channel info — comes last so RF/identity is grouped together at top
  if (ch) {
    if (ch.ref_signal_power_dbm != null) out.ref_signal_power = ch.ref_signal_power_dbm;
    if (ch.ul_power_attenuation_db != null) out.ul_power_attenuation = ch.ul_power_attenuation_db;
    if (ch.antenna_x != null || ch.antenna_y != null || ch.antenna_type) {
      out.antenna = {
        type: ch.antenna_type ?? 'isotropic',
        x: ch.antenna_x ?? 0,
        y: ch.antenna_y ?? 0,
      };
    }
    const dl: Record<string, unknown> = { type: ch.dl_type };
    if (ch.doppler_hz != null) dl.doppler_hz = ch.doppler_hz;
    if (ch.noise_floor_dbm_hz != null) dl.noise_floor = ch.noise_floor_dbm_hz;
    out.channel_dl = dl;
    out.channel_ul = { type: ch.ul_type };
  }
  return out;
}

function emitCellGroup(g: CellGroupSpec, channels: PerCellChannel[]): unknown {
  const out: Record<string, unknown> = {
    group_type: g.group_type,
    multi_ue: g.multi_ue,
  };
  if (g.multi_ue_type) out.multi_ue_type = g.multi_ue_type;
  if (g.cpu_core_list) out.cpu_core_list = g.cpu_core_list;
  if (g.rel13_5 != null) out.rel13_5 = g.rel13_5;
  if (g.pdcch_decode_opt != null) out.pdcch_decode_opt = g.pdcch_decode_opt;
  if (g.pdcch_decode_opt_threshold != null) {
    out.pdcch_decode_opt_threshold = g.pdcch_decode_opt_threshold;
  }
  if (g._extra) Object.assign(out, g._extra);
  // Cells with channel info, in stable key order
  out.cells = g.cells.map((c, i) => {
    const ch = channels.find(x => x.cell_index === i);
    return buildCellRecord(c, ch);
  });
  return out;
}

/**
 * Expand power_on events with `duration` into a power_on + power_off pair.
 * Strips the duration field from the power_on after emitting the pair.
 * Other event types pass through unchanged.
 *
 * The pair is sorted by start_time so the final array is monotonic.
 */
function expandDurationsToPowerOff(events: SimEvent[]): SimEvent[] {
  const expanded: SimEvent[] = [];
  for (const ev of events) {
    if (ev.event === 'power_on' && ev.duration != null && ev.duration > 0) {
      // Emit power_on without duration, then matching power_off
      const { duration, ...rest } = ev;
      expanded.push({ ...(rest as SimEvent) });
      expanded.push({
        event: 'power_off',
        start_time: ev.start_time + duration,
      });
    } else {
      // Strip duration field on non-power events for cleanliness
      const { duration: _d, ...rest } = ev;
      void _d;
      expanded.push(rest as SimEvent);
    }
  }
  return expanded.sort((a, b) => a.start_time - b.start_time);
}

function emitSimEvent(e: SimEvent): unknown {
  const base: Record<string, unknown> = {
    event: e.event,
    start_time: e.start_time,
  };
  if (e.loop_count != null) base.loop_count = e.loop_count;
  if (e.loop_delay != null) base.loop_delay = e.loop_delay;

  switch (e.event) {
    case 'pdn_connect':
    case 'pdn_disconnect':
      if (e.apn != null) base.apn = e.apn;
      if (e.pdn_type != null) base.pdn_type = e.pdn_type;
      break;
    case 'ext_app':
      base.prog = e.prog;
      if (e.args) base.args = e.args;
      if (e.tag) base.tag = e.tag;
      break;
    case 'flood':
      base.direction = e.direction;
      base.bitrate = e.bitrate;
      if (e.packet_size != null) base.packet_size = e.packet_size;
      break;
    case 'http':
      base.url = e.url;
      if (e.method) base.method = e.method;
      break;
    case 'voice':
      if (e.codec) base.codec = e.codec;
      break;
    case 'ping':
      base.destination = e.destination;
      if (e.count != null) base.count = e.count;
      if (e.interval != null) base.interval = e.interval;
      break;
    case 'handover':
      base.target_cell_id = e.target_cell_id;
      break;
  }
  if (e._extra) Object.assign(base, e._extra);
  return base;
}

function buildEventsForUe(
  ueId: number,
  assignments: UeAssignment[],
  templates: TrafficTemplate[],
): SimEvent[] {
  const a = assignments.find(x => x.ue_id === ueId);
  if (!a) return [];
  const tpl = templates.find(t => t.id === a.template_id);
  if (!tpl) return [];
  // Apply start_offset from the assignment
  const offset = a.start_offset ?? 0;
  const shifted = tpl.events.map(e => ({
    ...e,
    start_time: e.start_time + offset,
  }));
  return expandDurationsToPowerOff(shifted as SimEvent[]);
}

function emitUeListEntry(
  sub: SubscriberEntry,
  events: SimEvent[],
  mobility: UeMobility | undefined,
  userPlane: MaterializedProfile['userPlane'],
): unknown {
  const out: Record<string, unknown> = {
    as_release: sub.as_release,
    ue_category: sub.ue_category,
    sim_algo: sub.sim_algo,
    imsi: sub.imsi,
    K: sub.K,
  };
  if (sub.opc) out.opc = sub.opc;
  if (sub.amf) {
    // amf may be hex string like "0x9001" — emit as number if possible
    const v = sub.amf.startsWith('0x') ? parseInt(sub.amf, 16) : parseInt(sub.amf, 10);
    out.amf = Number.isFinite(v) ? v : sub.amf;
  }
  if (sub.sqn) out.sqn = sub.sqn;
  if (sub.ext_sim) out.ext_sim = sub.ext_sim;
  if (sub.sim_reader_index != null) out.sim_reader_index = sub.sim_reader_index;
  if (sub.default_nssai) out.default_nssai = sub.default_nssai;
  if (sub._extra) Object.assign(out, sub._extra);

  // User Plane plumbing per UE
  if (userPlane.mode === 'tun') {
    if (userPlane.tun_setup_script) out.tun_setup_script = userPlane.tun_setup_script;
    if (userPlane.tun_interface_name) out.tun_interface_name = userPlane.tun_interface_name;
  } else if (userPlane.mode === 'remote') {
    if (userPlane.rue_addr) out.rue_addr = userPlane.rue_addr;
    if (userPlane.rue_protocol) out.rue_protocol = userPlane.rue_protocol;
  }

  // Mobility
  if (mobility) {
    out.position = mobility.position;
    if (mobility.speed > 0) out.speed = mobility.speed;
    if (mobility.direction !== 0) out.direction = mobility.direction;
    if (mobility.antenna_type) out.antenna = { type: mobility.antenna_type };
    if (mobility.waypoints && mobility.waypoints.length > 0) {
      out.waypoints = mobility.waypoints;
    }
  }

  // Sim events
  if (events.length > 0) {
    out.sim_events = events.map(emitSimEvent);
  }
  return out;
}

function emitLogOptions(layers: LayerLogConfig[]): string {
  // Sorted: 'all' first, others alphabetical
  const sorted = [...layers].sort((a, b) => {
    if (a.layer === 'all') return -1;
    if (b.layer === 'all') return 1;
    return a.layer < b.layer ? -1 : 1;
  });
  const tokens: string[] = [];
  for (const l of sorted) {
    tokens.push(`${l.layer}.level=${l.level}`);
    tokens.push(`${l.layer}.max_size=${l.max_size}`);
  }
  return tokens.join(',');
}

// ────────────────────────────────────────────────────────────────────────────
// Public API
// ────────────────────────────────────────────────────────────────────────────

export function emitUeCfg(profile: MaterializedProfile, options: EmitOptions = {}): string {
  const { cell, subscriber, traffic, userPlane, channel, settings } = profile;

  // Top-level object
  const top: Record<string, unknown> = {};

  // Settings keys
  top.log_options = emitLogOptions(settings.log_layers);
  top.log_filename = settings.log_filename;
  top.com_addr = settings.com_addr;
  if (settings.com_auth) top.com_auth = true;
  if (settings.com_password) top.com_password = settings.com_password;
  top.tx_gain = settings.tx_gain;
  top.rx_gain = settings.rx_gain;
  if (settings.cpu_core_list) top.cpu_core_list = settings.cpu_core_list;
  if (settings.pdcch_decode_opt != null) top.pdcch_decode_opt = settings.pdcch_decode_opt;

  // RF driver
  const rfd: Record<string, unknown> = { name: settings.rf_driver.name };
  if (settings.rf_driver.args) rfd.args = settings.rf_driver.args;
  if (settings.rf_driver.sync) rfd.sync = settings.rf_driver.sync;
  if (settings.rf_driver.rx_antenna) rfd.rx_antenna = settings.rf_driver.rx_antenna;
  if (settings.rf_driver.fifo_tx_time != null) rfd.fifo_tx_time = settings.rf_driver.fifo_tx_time;
  if (settings.rf_driver.rx_latency != null) rfd.rx_latency = settings.rf_driver.rx_latency;
  top.rf_driver = rfd;

  // Cell groups (with channel info merged into each cell)
  top.cell_groups = cell.cell_groups.map((g, i) => {
    // Determine the index range of cells in this group's flat numbering
    const startIdx = cell.cell_groups.slice(0, i).reduce((s, gg) => s + gg.cells.length, 0);
    const groupChannels = channel.per_cell.filter(
      pc => pc.cell_index >= startIdx && pc.cell_index < startIdx + g.cells.length,
    ).map(pc => ({ ...pc, cell_index: pc.cell_index - startIdx }));
    return emitCellGroup(g, groupChannels);
  });

  // Custom bands
  if (cell.bands && cell.bands.length > 0) {
    top.bands = cell.bands.map((b: CustomBandSpec) => ({
      band: b.band,
      dl_low: b.dl_low,
      dl_high: b.dl_high,
      ul_low: b.ul_low,
      ul_high: b.ul_high,
      ...(b.dl_offset != null ? { dl_offset: b.dl_offset } : {}),
      ...(b.ul_offset != null ? { ul_offset: b.ul_offset } : {}),
    }));
  }

  // Channel sim master switches
  top.channel_sim = channel.channel_sim;
  if (channel.channel_sim) {
    top.delay_sim = channel.delay_sim;
  }

  // PDN list (lifted to top level)
  if (userPlane.pdn_list.length > 0) {
    top.pdn_list = userPlane.pdn_list.map(p => {
      const pdn: Record<string, unknown> = {
        access_point_name: p.apn,
        pdn_type: p.pdn_type,
      };
      if (p.default) pdn.default = true;
      return pdn;
    });
  }

  // Default address for traffic
  if (traffic.default_address) top.default_address = traffic.default_address;

  // ue_list — assemble each entry from subscriber + per-UE events + mobility
  top.ue_list = subscriber.ues.map(sub => {
    const events = buildEventsForUe(sub.ue_id, traffic.assignments, traffic.templates);
    const mob = channel.mobility.find(m => m.ue_id === sub.ue_id);
    return emitUeListEntry(sub, events, mob, userPlane);
  });

  // Pretty-print
  const body = emitObject(top, 0);

  const header = options.header
    ? `/* simtool — generated UE simulator configuration\n * ${new Date().toISOString()}\n */\n`
    : '';

  return header + body + '\n';
}
